apiVersion: v1
kind: ConfigMap
metadata: 
  name: db-host-cm
  namespace: expense
data:
  DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    project: expense
    environment: dev
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      project: expense
      environment: dev
      app: backend
  template:
    metadata:
      labels:
        project: expense
        environment: dev
        app: backend
    spec:
      containers:
        - name: backend
          image: cekharch/backend:v1
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-host-cm
                  key: DB_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: expense
  labels:
    project: expense
    environment: dev
    app: backend
spec:
  selector:
    project: expense
    environment: dev
    app: backend
  ports:
    - port: 80
      targetPort: 8080