apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  labels:
    containerz: "nginx-almalinux"
    project: expense
    environment: dev
spec:
  containers:
    - name: nginx
      image: nginx
    - name: almalinux
      image: almalinux:9
      command: ["sleep", "100"]

# The Pod "multi-container" is invalid: metadata.labels: Invalid value: "nginx,almalinux": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
