apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  labels:
    containers: "nginx,almalinux"
    project: expense
    environment: dev
spec:
  containers:
    - name: nginx
      image: nginx
    - name: almalinux
      image: almalinux:9