apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    environment: prod
    project: expense
  annotations:
    imageRegistry: registry.dockerhub.com
    buildUrl: https://jenkins.dev.com/build/7
spec:
  containers:
    - name: nginx
      image: nginx
      