apiVersion: v1
kind: Pod
metadata:
  name: getconfigmap
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - configMapRef:
            name: configmap
      # env:
      #   - name: course
      #     valueFrom:
      #       configMapKeyRef:
      #         name: configmap
      #         key: course
      #   - name: duration
      #     valueFrom:
      #       configMapKeyRef:
      #         key: duration
      #         name: configmap # name of the configmap created in 08-configmap yaml file
