apiVersion: v1
kind: Pod
metadata: 
  name: podsecret
spec: 
  containers:
    - name: nginx
      image: nginx
      env:
        - name: username
          valueFrom:
            secretKeyRef:
              key: username
              name: podsecret
        - name: password
          valueFrom:
            secretKeyRef:
              key: password
              name: podsecret