apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  labels:
    project: digital
    service: security
    environment: dev
spec:
  selector:
    project: digital
    environment: dev
    service: security
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80

# CusterIP is default type, it is useful for pod to pod communication