apiVersion: v1
kind: Service
metadata: 
  name: nodeportsrv
spec:
  type: NodePort
  selector:
    project: digital
    environment: dev
    service: security
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 32007 
      
# if we dont specify node port, k8s will assign random port in between the range 32000 - 32767.
# for this to work