apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-lb
spec:
  type: LoadBalancer
  selector:
    project: digital
    environment: dev
    service: security
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32007
