apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    project: digital
    environment: dev
    tier: frontend
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      project: digital
      environment: dev
      tier: frontend
      app: nginx
  template:
    metadata:
      labels:
        project: digital
        environment: dev
        tier: frontend
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    project: digital
    environment: dev
    app: frontend
spec:
  type: NodePort
  selector:
    project: digital
    environment: dev
    tier: frontend
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32007