apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels:
    project: expense
    environment: dev
    app: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      project: expense
      environment: dev
      app: mysql-db
  template:
    metadata:
      labels:
        project: expense
        environment: dev
        app: mysql-db
    spec:
      containers:
        - name: mysql
          image: cekharch/mysql:v1
      
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    project: expense
    environment: dev
    app: mysql-db
  ports:
    - name: mysql-port
      port: 3306
      targetPort: 3306