apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static-provisioner
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0b0b0385cd93a316e
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #       - matchExpressions:
  #           - key: topology.kubernetes.io/zone
  #             operator: In
  #             values:
  #               - us-east-2c
---

#AttachVolume.Attach failed for volume "ebs-static-provisioner" : rpc error: code = Internal desc = Could not attach volume "vol-0b0b0385cd93a316e" to node "i-02dd866e04295e47b": could not attach volume "vol-0b0b0385cd93a316e" to node "i-02dd866e04295e47b": operation error EC2: AttachVolume, https response error StatusCode: 400, RequestID: 160d2ea5-ae31-4aa3-8925-31b700ba50ca, api error InvalidVolume.ZoneMismatch: The volume 'vol-0b0b0385cd93a316e' is not in the same availability zone as instance 'i-02dd866e04295e47b'

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static-provisioner
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pvc
  labels:
    topic: ebs-static
spec:
  nodeSelector: 
    topology.kubernetes.io/zone: us-east-1f
  containers:
  - name: nginx-pv
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim
  
---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-svc
spec:
  type: LoadBalancer
  selector:
    topic: ebs-static
  ports:  
    - port: 80
      targetPort: 80