apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-cliam-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "expense-ebs"
  resources:
    requests:
      storage: 3Gi
  # volumeName: "expense-ebs"
  
---

apiVersion: v1
kind: Pod
metadata: 
  name: nginx-ebs-dynamic
  labels:
    purpose: ebs-dynamic
spec:
  # nodeSelector: 
  #   topology.kubernetes.io/zone: us-east-1f
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: pvc-ebs-dynamic
          mountPath: /usr/share/nginx/html
  volumes:
    - name: pvc-ebs-dynamic
      persistentVolumeClaim:
        claimName: ebs-cliam-dynamic

---
apiVersion: v1
kind: Service
metadata:
  name: ebs-dynamic
spec:
  selector:
    purpose: ebs-dynamic
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80